version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-1:529873347575:task-definition/mbp3-ec2:5"
        LoadBalancerInfo:
          ContainerName: "magento23"
          ContainerPort: 80
# Optional properties
#        PlatformVersion: "LATEST"
#        NetworkConfiguration:
#          AwsvpcConfiguration:
#            Subnets: ["subnet-1234abcd","subnet-5678abcd"]
#            SecurityGroups: ["sg-12345678"]
#            AssignPublicIp: "ENABLED"
#Hooks:
#  - BeforeInstall: "LambdaFunctionToValidateBeforeInstall"
#  - AfterInstall: "LambdaFunctionToValidateAfterTraffic"
#  - AfterAllowTestTraffic: "LambdaFunctionToValidateAfterTestTrafficStarts"
#  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeAllowingProductionTraffic"
#  - AfterAllowTraffic: "LambdaFunctionToValidateAfterAllowingProductionTraffic"