version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - IMAGE_TAG=$(grep FROM Dockerfile | awk -F ':' '{print $2}')
      - echo IMAGE_TAG is $IMAGE_TAG
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - IMAGE_TAG=$(grep FROM Dockerfile | awk -F ':' '{print $2}')
      - echo IMAGE_TAG is $IMAGE_TAG
      - TAG_ID=$(echo $IMAGE_TAG"_"`date +"%s"`)
      - echo docker build -t $IMAGE_REPO_NAME:$TAG_ID .
      - docker build -t $IMAGE_REPO_NAME:$TAG_ID .
      - docker tag $IMAGE_REPO_NAME:$TAG_ID $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$TAG_ID    
      - docker tag $IMAGE_REPO_NAME:$TAG_ID $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$TAG_ID
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo Writing image definitions file...
      - printf '[{"name":"magento23","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$TAG_ID > imageDetail.json
artifacts:
    files: imageDetail.json
    files: appspec.yaml
    
      