steps:
# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/magento:$SHORT_SHA'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/magento:7.3.20'
  - '.'

# This step pushes the image to Artifact Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/magento:$SHORT_SHA'

# create image attestation   
- id: 'create-attestation'
  name: 'gcr.io/${PROJECT_ID}/binauthz-attestation:latest'
  args:
    - '--artifact-url'
    - 'gcr.io/${PROJECT_ID}/magento:$SHORT_SHA'
    - '--attestor'
    - 'projects/${PROJECT_ID}/attestors/built-by-cloud-build'
    - '--keyversion'
    - 'projects/${PROJECT_ID}/locations/asia-southeast1/keyRings/moonshot/cryptoKeys/attest/cryptoKeyVersions/1'

# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=magento-deploy.yaml
  - --image=gcr.io/$PROJECT_ID/magento:$SHORT_SHA
  - --location=asia-southeast1
  - --cluster=cluster-1
  
timeout: 900s
options:
  pool:
    name: 'projects/${PROJECT_ID}/locations/asia-southeast1/workerPools/yantk-p-pool'
    
